language: python

cache:
  pip: true
  apt: true
  directories:
    - ~/visbrain_data

sudo: false
dist: trusty
python:
    - '3.6'


matrix:
  include:
    - env: TEST=standard
      os: linux
    # - env: TEST=standard
    #   os: linux
    #   python: '3.7'
    - env: TEST=flake
      os: linux
    # - env: TEST=standard
    #   os: osx
    - env: TEST=examples
      os: linux
  allow_failures:
    - env: TEST=flake


before_install:
    # See https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI :
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
    # Instal miniconda3 :
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - SRC_DIR=$(pwd)


install:
    # Create the py3 environnement ;
    - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION numpy scipy pip cython
    - source activate testenv
    # Install dependencies :
    - if [ "${TEST}" == "standard" ] || [ "${TEST}" == "examples" ]; then
        pip install codecov pytest pytest-cov pytest-sugar pytest-travis-fold openpyxl xlrd;
        pip install mne nibabel pandas tensorpac scikit-image imageio lxml;
        pip install git+https://github.com/hbldh/lspopt.git#egg=lspopt;
      fi;
    - if [ "${TEST}" == "flake" ]; then
        pip install flake8 pep8-naming;
      fi;
    # Install latest version vispy :
    - pip install git+https://github.com/vispy/vispy.git
    - pip install PyOpenGL PyOpenGL_accelerate
    # - pip install -q freetype-py husl pypng cassowary imageio
    # ------------------- VISBRAIN -------------------
    - cd ${SRC_DIR}
    - pip install -e .


before_script:
    # See https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI :
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

script:
    - if [[ "${TEST}" == "standard" ]]; then
          py.test --cov;
      elif [[ "${TEST}" == "flake" ]]; then
          flake8;
      elif [[ "${TEST}" == "examples" ]]; then
          make examples;
      fi;


notifications:
    email: false
    slack: visbrainteam:lHdzZcFmXQczGlxJEDtQYqv9


after_success:
    - if [ "${TEST}" == "standard" ]; then
        codecov;
      fi
